[book]
authors = ["crumblingstatue"]
language = "en"
multilingual = false
src = "src"
title = "Hexerator"

[output.html]
git-repository-url = "https://github.com/crumblingstatue/hexerator-book"

[build]
build-dir = "../docs"
